title: Diocese of Kalookan
tagline: Roman Catholic Diocese of Kalookan
description: Official website of the Diocese of Kalookan.

# This is the most important part for fixing the 404s
url: "https://kaela-4650.github.io"
baseurl: "/rcdok-website"

author:
  name: RCDOK
  facebook: rcdok

theme: jekyll-theme-chirpy

# This tells the theme to use the folder name for all links
path_type: relative
